"""add logo upload url and public id

Revision ID: 31b19f3703d4
Revises: 4dff2eae7a62
Create Date: 2026-05-13 19:20:05.484231

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "31b19f3703d4"
down_revision: str | None = "4dff2eae7a62"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organiser_templates",
        sa.Column("logo_url", sa.String(length=1024), nullable=True),
    )
    op.add_column(
        "organiser_templates",
        sa.Column("logo_public_id", sa.String(length=512), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organiser_templates", "logo_public_id")
    op.drop_column("organiser_templates", "logo_url")
    # ### end Alembic commands ###
